# Generated by Django 4.2.10 on 2024-04-28 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('avg', models.FloatField()),
                ('create_date', models.DateField(default=datetime.datetime(2024, 4, 28, 12, 46, 1, 844893))),
            ],
        ),
    ]
