# Generated by Django 5.0.3 on 2024-05-11 19:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('credits', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 19, 15, 1, 76215)),
        ),
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.course')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.student')),
            ],
        ),
    ]
