# Generated by Django 5.0.3 on 2024-05-11 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_course_student_user_alter_student_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreg',
            old_name='courseCode',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentreg',
            old_name='studentId',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 21, 52, 11, 444176)),
        ),
    ]
