# Generated by Django 4.2.10 on 2024-03-30 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('avg', models.FloatField()),
                ('create_date', models.DateField(default=datetime.datetime(2024, 3, 31, 0, 2, 55, 642806))),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
