# Generated by Django 4.2.10 on 2024-04-21 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_student_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 21, 14, 11, 55, 796520)),
        ),
    ]
