# Generated by Django 4.2.10 on 2024-04-25 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_student_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 25, 13, 10, 18, 806878)),
        ),
    ]
